# Generated by Django 6.0.2 on 2026-02-10 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=100)),
                ('is_core', models.BooleanField(default=False)),
                ('criticality', models.CharField(max_length=50)),
                ('lifecycle_status', models.CharField(max_length=50)),
                ('business_owner', models.CharField(max_length=255)),
                ('it_owner', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('environments', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('hosting', models.CharField(max_length=100)),
                ('tech_stack', models.TextField()),
                ('database', models.CharField(max_length=255)),
                ('runtime', models.CharField(max_length=255)),
                ('capabilities', models.TextField()),
                ('tech_debt', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=100)),
                ('data_sensitivity', models.CharField(max_length=100)),
                ('source_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_integrations', to='portfolio.application')),
                ('target_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_integrations', to='portfolio.application')),
            ],
        ),
    ]
