# Generated by Django 6.0.2 on 2026-02-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integration',
            old_name='source_app',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='integration',
            old_name='target_app',
            new_name='target',
        ),
        migrations.RemoveField(
            model_name='integration',
            name='integration_type',
        ),
        migrations.AddField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('API', 'API'), ('File', 'File Transfer'), ('Message', 'Message Queue')], default='API', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='integration',
            name='data_sensitivity',
            field=models.CharField(max_length=50),
        ),
    ]
