# Generated by Django 6.0.2 on 2026-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_source_app_integration_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='data_sensitivity',
            field=models.CharField(choices=[('Low', 'Nízká (Veřejná data)'), ('Standard', 'Standardní (Interní)'), ('High', 'Vysoká (GDPR / Citlivé)')], default='Standard', max_length=50),
        ),
    ]
